### ISSUE TITLE
Error when running

### ISSUE THREAD

**Issue by vietalj** [CristianoYL/RestaurantAppAPI#1]
I have done everything and when I start app in the logs is see this:
[takeawayz-logs-1552396294948.txt](https://github.com/CristianoYL/RestaurantAppAPI/files/2956951/takeawayz-logs-1552396294948.txt)

Thank you so much for your support !

**Comment by CristianoYL** [comment]
It could be due to breaking changes in the **psycopg2** lib. I haven't maintained this project for a while so some of the libs can be very outdated. Feel free to remove the version numbers and install the latest versions, it should work fine since I only used the most basic features.

**Comment by vietalj** [comment]
Yup , it's works !

Could you give a tip how should looks path for restaurant logo and menu images ?

Thank you so much :)

**Comment by CristianoYL** [comment]
Sorry, I'm not sure if I understand your question. If you're asking about the format of the image paths, it's all using relative paths. 
The root folder is configured in [L42 in app.py](https://github.com/CristianoYL/RestaurantAppAPI/blob/master/code/app.py#L42)
The image control logic is defined in `code/models/image.py`

**Comment by vietalj** [comment]
Thank you so much for your reply!
I want to know how to add images for menus and shops. Just in case I just started learning python and java and took your project for example, and little bit don't understand. Where and how add images for restaurants. 
I already added one restaurant through database but app shows me image which one goes standart.

**Comment by CristianoYL** [comment]
You'll need to see the API reference. All operations should be done through HTTP requests, not database.
