### ISSUE TITLE
Logo and menu images path

### ISSUE THREAD

**Issue by vietalj** [CristianoYL/RestaurantAppAPI#2]
Hello Li Yin.

I've got a problem with menu images 
**"GET /images/menu/1 HTTP/1.1" 404 -**
I cannot understand how should looks path for menu and restaurant logo images. Could you explain to me, please? I'm beginner 

Thank you so much for your help.

**Comment by vietalj** [comment]
Sorted!

Needed to create a folder in API /static/images/menu/
and
Add an image with a name menu_[id].jpg


Close topic!

**Comment by CristianoYL** [comment]
Hi @vietalj, that's right. It is configured with ** UPLOADED_MENU_DEST** in [line 42 of app.py](https://github.com/CristianoYL/RestaurantAppAPI/blob/master/code/app.py#L42).

I'm closing this issue since you've figured it out.

Cheers.
