### ISSUE TITLE
Order

### ISSUE THREAD

**Issue by vietalj** [CristianoYL/RestaurantAppAPI#3]
Hiya

I successfully launched the project but I've got a problem with the order.

What happening when I try to do login.

`sqlalchemy.exc.InvalidRequestError: When initializing mapper Mapper|OrderModel|order, expression 'Menu' failed to locate a name ("name 'Menu' is not defined"). If this is a class name, consider adding this relationship() to the <class 'models.order.OrderModel'> class after both dependent classes have been defined.`

**Comment by CristianoYL** [comment]
I think the `menu` table is in lowercase. I didn't fully implement the order logic in the repo. You may want to add your work there.
